# Generated by Django 3.1.2 on 2021-05-31 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rating',
        ),
        migrations.AddField(
            model_name='rating',
            name='gender',
            field=models.IntegerField(choices=[('1', 'Like'), ('-1', 'Dislike')], null=True),
        ),
    ]
